### ISSUE TITLE
parameters metaontrack

### ISSUE THREAD

**Issue by ichaouch** [MaestSi/ONTrack#7]
hello simone,

i was wondering if you could explain what these parameters for the metaontrack mean?  
"change cut -d" " -f2,3 (line 47) and cut -d" " -f2 (line 48) to cut -d" " -f1,2 and cut -d" " -f1 respectively"

kind regards, Imane

**Comment by MaestSi** [comment]
Dear Imane,
thanks for asking. I actually realised that the choice of which fields needed to be extracted from the Blast output did not depend on the content of the database, but on the version of the Blast database instead (version 5 VS older versions, I think). If you recently built or downloaded a Blast indexed database, then cut -d" " -f1,2 and cut -d" " -f1 would be the right choices. Let me know if this works for your database. If you need any help for indexing a Blast database, please have a look at [this repository](https://github.com/MaestSi/MetaBlast).
Best,
Simone

**Comment by ichaouch** [comment]
hello, 
thanks for answering, when i downloaded version 4 of the database it worked.

**Comment by MaestSi** [comment]
Perfect!
Best,
Simone
