### ISSUE TITLE
Installer takes for ages

### ISSUE THREAD

**Issue by thierryjanssens** [MaestSi/ONTrack#8]
Hi all,

I am trying to install the ONTrack pipeline, but the installer takes for ages and seems to hang:

![image](https://user-images.githubusercontent.com/38220376/145395509-36f716f1-059b-4541-ab5b-e6334279ad06.png)

I am able to install other conda environments easily.

Kind regards,

T.

**Comment by MaestSi** [comment]
Hi,
I just updated the **install.sh** script, please try it out and see if it works. I realized samtools was not working in the newly created environment (samtools -h complained about missing libcrypto.1.0.0.dylib library), and I fixed it by creating a symbolic link pointing to libcrypto.1.1.dylib with:
`ln -s /path/to/ONTrack_env/lib/libcrypto.1.1.dylib /path/to/ONTrack_env/lib/libcrypto.1.0.0.dylib`
Please let me know if this works also for you.
Best,
Simone

**Comment by thierryjanssens** [comment]
Thank you Simone,

this has worked!
