### ISSUE TITLE
add the the percent identity (%) column to the Blast search results

### ISSUE THREAD

**Issue by dieunelderilus** [MaestSi/ONTrack#9]
Hello  ONTrack developer- 

I have successfully ran ONTrack on my dataset, but I want to add the  **_'percent identity(%)_**'  to my BLAST search results generated by  ONTrack.  Is there a specific  way to manage this?

Thanks, 
~DD

**Comment by MaestSi** [comment]
Hi,
if I understand correctly, you are able to run also the Blast search. If I'm not wrong, the chosen Blast output format should already be reporting the percent identity. Can you please provide an example and tell me what would you like to see? Thanks,
Simone

**Comment by dieunelderilus** [comment]
Hello Simone, 
Thank you for your quick response. My Blast output file contains four (4) columns :  accession number, Description, bit score and E value.  I would hope to have a 5th column showing the percent of identity between my query consensus contig and the sequence in the database. 
An example of my Blast result is attached  bellow:

[BC03.blastn.txt](https://github.com/MaestSi/ONTrack/files/7998293/BC03.blastn.txt)

**Comment by MaestSi** [comment]
Hi,
I understand it is a formatting issue, right? The information about percent identity is already in the file: after all the hits, you have the alignments in the same order, and there you have "Identities = xx (yy%)". But if you prefer to have Blast results in a tabular format, you may change line 257 in **ONTrack.R** script from:
`system(paste0(BLASTN, " -num_threads ", num_threads, " -db ", NTDB, " -query ", final_contig, " > ", blast_results))`
to:
`system(paste0(BLASTN, " -num_threads ", num_threads, " -db ", NTDB, " -query ", final_contig, " -outfmt \"6 qseqid stitle bitscore qcovs evalue pident slen saccver qlen\" > ", blast_results))`
Let me know if this helps!
Best,
Simone

**Comment by dieunelderilus** [comment]
Hello Simone - Thank you very much, this helps a lot! Now I can manage the format of my Blast output!

Cheers,
~DD

**Comment by MaestSi** [comment]
Perfect, I will close the issue!
Ciao,
Simone
